### ISSUE TITLE
Указать и пригласить соавтора

### ISSUE THREAD

**Issue by FlashAnton** [m1razh/Web-programming#1]
Здравствуйте!

Вашей бригаде присвоен вариант №13.
Укажите, пожалуйста, кто будет работать с Вами в бригаде, в README-файле.
Пригласите его коллаборатором в этот репозиторий.
Продублируйте, пожалуйста, информацию в этой ветке обсуждений.

**Comment by m1razh** [comment]
Здравствуйте, README обновил
Напарника пригласил
